# Generated by Django 5.0.6 on 2026-04-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_ebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHubCategory',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Knowledge Hub Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTool',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('tags', models.JSONField(default=list)),
                ('pricing', models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid')], default='free', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='portfolio.knowledgehubcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
