# Generated by Django 5.0.6 on 2026-04-24 16:31

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_service_image_alter_ebook_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[portfolio.validators.validate_image_size]),
        ),
    ]
