# Generated by Django 5.0.6 on 2026-04-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Open to opportunities', max_length=100)),
                ('heading', models.CharField(default="Let's build something amazing together", max_length=255)),
                ('button_text', models.CharField(default='Get in touch', max_length=100)),
                ('button_url', models.CharField(default='/contact', max_length=255)),
            ],
            options={
                'verbose_name': 'Footer CTA',
                'verbose_name_plural': 'Footer CTA',
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('GitHub', 'GitHub'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twitter/X'), ('YouTube', 'YouTube'), ('Email', 'Email'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('external', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.footersection')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
