# Generated by Django 5.0.6 on 2026-04-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('shortDesc', models.TextField()),
                ('longDesc', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(default=list)),
                ('techStack', models.JSONField(default=list)),
                ('categories', models.JSONField(default=list)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('links', models.JSONField(default=dict)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('highlights', models.JSONField(default=list)),
            ],
        ),
    ]
