# Generated by Django 5.0.6 on 2026-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_abouthighlight_aboutstat_bioparagraph_whatido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('skills', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('techs', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tech Stack Category',
                'verbose_name_plural': 'Tech Stack Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('education', 'Education'), ('work', 'Work'), ('milestone', 'Milestone'), ('launch', 'Launch')], max_length=20)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
