# Generated by Django 5.0.6 on 2026-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('cta', models.CharField(default='Learn More', max_length=100)),
                ('cta_link', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
