# Generated by Django 5.0.6 on 2026-04-24 14:19

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', validators=[portfolio.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='icon',
            field=models.ImageField(upload_to='ebooks/', validators=[portfolio.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[portfolio.validators.validate_image_size]),
        ),
    ]
