# Generated by Django 5.0.6 on 2026-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_service_image_alter_ebook_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AlterField(
            model_name='ebook',
            name='icon',
            field=models.URLField(),
        ),
    ]
