# Generated by Django 4.2 on 2026-05-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_footercta_footersection_navbarlink_sociallink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pricing',
        ),
        migrations.AddField(
            model_name='service',
            name='tiers',
            field=models.JSONField(default=list),
        ),
    ]
