# Generated by Django 4.2 on 2026-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_service_pricing_service_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beforeAfterImages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='mobileDesktopPreviews',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
