# Generated by Django 4.2 on 2026-06-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0020_assessmentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('general', 'General Question'), ('content', 'Content Request'), ('technical', 'Technical Issue'), ('premium', 'Premium Inquiry'), ('feedback', 'Feedback / Suggestion'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='SupportTicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('read_by_student', models.BooleanField(default=False)),
                ('read_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='portfolio.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
