# Generated by Django 4.2 on 2026-06-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_supportticket_status_alter_supportticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='Briefcase', max_length=50),
        ),
    ]
