from django.core.management.base import BaseCommand
from portfolio.models import EBook


class Command(BaseCommand):
    help = 'Seed eBook data'

    def handle(self, *args, **options):
        ebooks_data = [
            {
                'slug': 'html-css-guide',
                'title': 'HTML & CSS Complete Guide',
                'subtitle': 'Build Beautiful Websites from Scratch',
                'description': 'A hands-on walkthrough of modern HTML5 and CSS3 — semantic markup, the box model, Flexbox, CSS Grid, and responsive design. Packed with quizzes and real-world projects to cement every concept.',
                'category': 'Web Development',
                'tags': ['HTML5', 'CSS3', 'Flexbox', 'CSS Grid', 'Responsive'],
                'gradient': 'from-orange-500 to-red-500',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/HTMLCSS/',
                'is_free': True,
                'order': 0,
            },
            {
                'slug': 'javascript-guide',
                'title': 'JavaScript: Zero to Pro',
                'subtitle': 'Master Modern JavaScript ES6+',
                'description': 'From variables, functions and loops to DOM manipulation and HTML forms — a structured 5-chapter journey through JavaScript fundamentals with hands-on examples every step of the way.',
                'category': 'Web Development',
                'tags': ['JavaScript', 'ES6+', 'DOM', 'Functions', 'Forms'],
                'gradient': 'from-yellow-300 to-yellow-500',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/JAVASCRIPT/',
                'is_free': True,
                'order': 1,
            },
            {
                'slug': 'django-flask-guide',
                'title': 'Django Web Framework',
                'subtitle': 'Full-Stack Python Web Development',
                'description': 'Build production-ready web apps with Django — models, views, templates, ORM, authentication, and REST APIs. Also covers Flask as a companion lightweight framework.',
                'category': 'Web Development',
                'tags': ['Django', 'Python', 'Flask', 'ORM', 'REST API'],
                'gradient': 'from-green-600 to-emerald-800',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg',
                'icon_white': True,
                'read_url': 'https://aman-0402.github.io/Django/',
                'is_free': True,
                'order': 2,
            },
            {
                'slug': 'flask-guide',
                'title': 'Flask Microframework',
                'subtitle': 'Lightweight Python APIs & Web Apps',
                'description': 'Build lightweight, fast web APIs and apps with Flask. Covers routing, Jinja2 templates, SQLAlchemy, Blueprints, and deploying Flask applications to production environments.',
                'category': 'Web Development',
                'tags': ['Flask', 'Python', 'Jinja2', 'SQLAlchemy', 'Blueprints'],
                'gradient': 'from-slate-500 to-slate-800',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg',
                'icon_white': True,
                'read_url': 'https://aman-0402.github.io/Django/contents/Flask/content.html',
                'is_free': True,
                'order': 3,
            },
            {
                'slug': 'python-data-science',
                'title': 'Python for Data Science',
                'subtitle': 'NumPy, Pandas, Matplotlib & Beyond',
                'description': '17-chapter Python journey — from syntax basics through OOP, NumPy, Pandas, Matplotlib, Web APIs, and database connectivity. Includes mock exams and IBM Python Certification practice tests.',
                'category': 'Data Science & AI',
                'tags': ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'IBM Certification'],
                'gradient': 'from-blue-500 to-indigo-600',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/Python/',
                'is_free': True,
                'order': 4,
            },
            {
                'slug': 'statistics-guide',
                'title': 'Statistics for Data Science',
                'subtitle': 'Probability, Inference & Analytics',
                'description': 'Master the statistical foundations every data scientist needs — probability distributions, hypothesis testing, correlation, regression analysis, and Bayesian thinking with real-world examples.',
                'category': 'Data Science & AI',
                'tags': ['Statistics', 'Probability', 'Hypothesis Testing', 'Regression', 'Analytics'],
                'gradient': 'from-violet-500 to-purple-700',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/Stats/',
                'is_free': True,
                'order': 5,
            },
            {
                'slug': 'aws-guide',
                'title': 'AWS Cloud Essentials',
                'subtitle': 'Amazon Web Services from Zero',
                'description': 'Get cloud-ready with AWS core services — EC2, S3, IAM, Lambda, RDS, and CloudWatch — with hands-on examples and real infrastructure patterns. Designed for developers new to cloud.',
                'category': 'Cloud & DevOps',
                'tags': ['AWS', 'EC2', 'S3', 'Lambda', 'IAM', 'Cloud'],
                'gradient': 'from-orange-400 to-amber-600',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/AWS/',
                'is_free': True,
                'order': 6,
            },
            {
                'slug': 'github-guide',
                'title': 'Git & GitHub Mastery',
                'subtitle': 'Version Control for Every Developer',
                'description': 'Everything about Git and GitHub — branching strategies, pull requests, merge conflict resolution, GitHub Actions CI/CD, and collaborative workflows used by real development teams.',
                'category': 'Cloud & DevOps',
                'tags': ['Git', 'GitHub', 'CI/CD', 'Branching', 'Version Control'],
                'gradient': 'from-zinc-600 to-zinc-900',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
                'icon_white': True,
                'read_url': 'https://aman-0402.github.io/Github/',
                'is_free': True,
                'order': 7,
            },
            {
                'slug': 'java-guide',
                'title': 'Java Programming',
                'subtitle': 'Core Java from Fundamentals to Advanced',
                'description': '17-chapter interactive Java guide — from syntax and OOP through Collections, Exception Handling, Java 8 features, Multithreading, and GUI with Swing. Ends with real capstone mini-projects.',
                'category': 'Languages',
                'tags': ['Java', 'OOP', 'Collections', 'Java 8', 'Multithreading'],
                'gradient': 'from-red-500 to-orange-600',
                'icon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/JavaEbook/',
                'is_free': True,
                'order': 8,
            },
            {
                'slug': 'networking-guide',
                'title': 'Computer Networking',
                'subtitle': 'Protocols, Architectures & the Web',
                'description': 'Understand how the internet works — OSI model, TCP/IP, DNS, HTTP/HTTPS, CISCO networking fundamentals, routing, subnetting, and the basics of network security every developer should know.',
                'category': 'Networking',
                'tags': ['TCP/IP', 'OSI Model', 'DNS', 'CISCO', 'HTTP/HTTPS'],
                'gradient': 'from-cyan-500 to-teal-700',
                'icon': 'https://cdn.simpleicons.org/cisco/ffffff',
                'icon_white': False,
                'read_url': 'https://aman-0402.github.io/Networking/',
                'is_free': True,
                'order': 9,
            },
        ]

        EBook.objects.all().delete()

        for data in ebooks_data:
            EBook.objects.create(**data)

        self.stdout.write(self.style.SUCCESS(f'[SUCCESS] Seeded {len(ebooks_data)} eBooks'))
